### ISSUE TITLE
OS X support broken by c2a48be

### ISSUE THREAD

**Issue by rickard-von-essen** [hpcloud/tail#37]
tail__.go and watch/polling__.go only builds on Windows/Linux. Build fails on OS X(darwin) with

```
go test -v ./...
# github.com/ActiveState/tail/watch
watch/polling.go:73: undefined: permissionErrorRetry
# _/Users/rickard/src/go-code/src/github.com/ActiveState/tail/watch
watch/polling.go:73: undefined: permissionErrorRetry
FAIL    github.com/ActiveState/tail [build failed]
make: *** [test] Error 2
```

Error was introduced in: c2a48be73929ce9609aa3a523c020a31a950566d
